### ISSUE TITLE
Storing data below stack pointer is not safe

### ISSUE THREAD

**Issue by jnk0le** [Ko-/aes-armcortexm#3]
Bitsliced and bsmaked subbytes puts temporary data below stack pointer, where it can be corrupted due to interrupts stacking context.

Allocating stack by `sub sp, #xx` and `add sp, #xx`, at the beginning and end of functions, will cost 2 extra cycles unless some magic with pre/post indexing is done.

**Comment by Ko-** [comment]
Good point. That it can be encoded in an instruction does not mean that I should do it. I can't find anything in the ABI for 32-bit ARM about the existence of a red zone under the stack pointer, so I will fix this as soon as I have time.

**Comment by Ko-** [comment]
It should be fixed now.
